services:
  database:
    image: mysql:5.7
    container_name: kaddem-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddem
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "database"]
      interval: 5s
      timeout: 10s
      retries: 20  
    networks:
      - kaddem-net

  pro-kaddem:
    image: nousseiba/kaddem:1.0.0
    container_name: kaddem-app
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/kaddem?useSSL=false&createDatabaseIfNotExist=true&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8089:8089"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8089/kaddem/actuator/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
    volumes:
      - ./logs:/app/logs
    networks:
      - kaddem-net

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - pro-kaddem
    networks:
      - kaddem-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Sarra@noussa123
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_DATASOURCES_DEFAULT_TYPE=prometheus
      - GF_DATASOURCES_DEFAULT_URL=http://localhost:9090
      - GF_DATASOURCES_DEFAULT_ACCESS=proxy
      - GF_DATASOURCES_DEFAULT_IS_DEFAULT=true
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - kaddem-net


volumes:
  mysql_data:
  grafana-data:

networks:
  kaddem-net:
    driver: bridge
