global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pro-kaddem:8089']
        labels:
          application: 'pro-kaddem'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']